## USING oznu/guacamole DOCKER CONTAINER
## MAKE A DIRECTORY IN THE GUACAMOLE FOLDER; CONFIG
## CREATE A DOCKER-COMPOSE.YML FILE WITH THE CONTENTS BELOW
## RUN THE CONTAINER USING FROM THE DIRECTORY OF THE YML FILE: docker-compose up -d 
## FOLLOW THE CERTBOT INSTRUCTIONS TO COMPLETE THE CERTIFICATE VALIDATION

## <-PASTE BELOW TEXT INTO A NGINX.YML FILE-> 
# docker-compose.yml
---
version: "2"
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - /DOCKER-PATH/guacamole/config:/config
