## USING danieldent/nginx-ssl-proxy
## MAKE TWO DIRECTORIES IN NGINX FOLDER; CONF AND LETSENCRYPT
## CHANGE THE SERVERNANME AND VOLUME NAMES BELOW
## CREATE A DOCKER-COMPOSE.YML FILE WITH THE CONTENTS BELOW
## RUN THE CONTAINER USING FROM THE DIRECTORY OF THE YML FILE: docker-compose up -d 
## LOG INTO THE CONTAINER USING: docker exec -it nginx_proxy /bin/bash
## RUN THIS COMMAND TO GENERATE A SSL CERTIFICATE: certbot -d www.zabelsa.com --manual --preferred-challenges dns certonly
## FOLLOW THE CERTBOT INSTRUCTIONS TO COMPLETE THE CERTIFICATE VALIDATION

## <-PASTE BELOW TEXT INTO A NGINX.YML FILE->

# docker-compose.yml
---
version: "2"
services:
  sslproxy:
    image: danieldent/nginx-ssl-proxy
    container_name: nginx_proxy
    restart: unless-stopped
    environment:
      #UPSTREAM
      SERVERNAME: WWW.DOMAINNAME.COM
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /DOCKER-PATH/nginx/conf:/etc/nginx/conf.d
      - /DOCKER-PATH/nginx/letsencrypt:/etc/letsencrypt
